"""Restricted assignment for the Binding Test's canonical yoke block.

The canonical construction retains eight valid-baseline sessions from one
prospectively defined stratum: four chose ``L`` and four chose ``H``.  Four
sessions are assigned to self-contingent execution (exactly two of each
baseline choice); the remaining four are yoke recipients.  Every schedule
generated by a self session is copied to exactly one yoke recipient.

Donor identity is part of a joint assignment.  This matters when two donors
share a canonical L/H label but differ on other frozen schedule attributes:
the yoke arm then receives the exact donor-schedule multiset rather than only
matching its aggregate L/H counts.
"""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
from fractions import Fraction
from functools import lru_cache
from itertools import combinations, permutations
import random
from typing import Iterable, Literal, Sequence, cast


LOW = "L"
HIGH = "H"
SELF = "self"
YOKE = "yoke"

Choice = Literal["L", "H"]
Arm = Literal["self", "yoke"]
AttritionReason = Literal["invalid_baseline", "unmatched_block_support"]

CANONICAL_BLOCK_SIZE = 8
CANONICAL_CHOICE_COUNT = 4
CANONICAL_ARM_SIZE = 4
CANONICAL_ALLOWED_ASSIGNMENT_COUNT = 576


@dataclass(frozen=True, slots=True)
class Session:
    """A pre-randomization session record.

    ``baseline_choice`` is intentionally typed as ``str`` so block formation
    can report invalid/unavailable records as attrition.  A ``CanonicalBlock``
    accepts only ``L`` and ``H``.  ``stratum`` must encode every prospectively
    frozen exact blocking factor (for example model, target family, and item
    pair); this module does not infer or tolerance-match omitted covariates.
    """

    session_id: str
    stratum: str
    baseline_choice: str

    def __post_init__(self) -> None:
        if not self.session_id:
            raise ValueError("session_id must be nonempty")
        if not self.stratum:
            raise ValueError("stratum must be nonempty")


@dataclass(frozen=True, slots=True)
class CanonicalBlock:
    """Eight retained sessions with exactly four L and four H choices."""

    block_id: str
    stratum: str
    sessions: tuple[Session, ...]

    def __post_init__(self) -> None:
        if not self.block_id:
            raise ValueError("block_id must be nonempty")
        if not self.stratum:
            raise ValueError("stratum must be nonempty")
        if len(self.sessions) != CANONICAL_BLOCK_SIZE:
            raise ValueError("a canonical block must contain exactly 8 sessions")

        session_ids = [session.session_id for session in self.sessions]
        if len(set(session_ids)) != len(session_ids):
            raise ValueError("session IDs must be unique within a block")
        if any(session.stratum != self.stratum for session in self.sessions):
            raise ValueError("all block sessions must belong to the block stratum")

        counts = _choice_counts(self.sessions)
        if set(counts) - {LOW, HIGH}:
            raise ValueError("canonical block choices must all be L or H")
        if counts[LOW] != CANONICAL_CHOICE_COUNT or counts[HIGH] != CANONICAL_CHOICE_COUNT:
            raise ValueError("a canonical block must contain exactly 4 L and 4 H choices")


@dataclass(frozen=True, slots=True)
class AttritionRecord:
    """A session excluded before randomization, with a machine-readable reason."""

    session: Session
    reason: AttritionReason
    detail: str


@dataclass(frozen=True, slots=True)
class BlockFormation:
    """Deterministic retained blocks and the complete pre-randomization attrition."""

    blocks: tuple[CanonicalBlock, ...]
    attrition: tuple[AttritionRecord, ...]
    input_session_count: int

    @property
    def retained_session_count(self) -> int:
        return sum(len(block.sessions) for block in self.blocks)

    @property
    def attrited_session_count(self) -> int:
        return len(self.attrition)

    @property
    def accounts_for_all_sessions(self) -> bool:
        return self.retained_session_count + self.attrited_session_count == self.input_session_count


@dataclass(frozen=True, slots=True)
class SessionAssignment:
    """The arm and executed schedule assigned to one retained session."""

    session_id: str
    baseline_choice: Choice
    arm: Arm
    received_schedule: Choice
    donor_session_id: str

    @property
    def is_match(self) -> bool:
        """Whether the received schedule has the recipient's baseline label."""

        return self.baseline_choice == self.received_schedule


@dataclass(frozen=True, slots=True)
class JointAssignment:
    """One member of a block's complete allowed joint assignment set."""

    block_id: str
    allowed_set_index: int
    sessions: tuple[SessionAssignment, ...]

    def for_session(self, session_id: str) -> SessionAssignment:
        for assignment in self.sessions:
            if assignment.session_id == session_id:
                return assignment
        raise KeyError(session_id)


@dataclass(frozen=True, slots=True)
class SessionProbabilityAudit:
    """Exact marginal and conditional probabilities for one session."""

    session_id: str
    p_self: Fraction
    p_yoke: Fraction
    p_receive_high_given_yoke: Fraction
    p_receive_low_given_yoke: Fraction
    p_match_given_yoke: Fraction
    p_mismatch_given_yoke: Fraction

    @property
    def has_both_yoke_exposure_classes(self) -> bool:
        return self.p_match_given_yoke > 0 and self.p_mismatch_given_yoke > 0


@dataclass(frozen=True, slots=True)
class AssignmentProbabilityAudit:
    """Exact enumeration audit for an allowed assignment set."""

    total_assignments: int
    unique_assignment_count: int
    sessions: tuple[SessionProbabilityAudit, ...]

    @property
    def is_canonical(self) -> bool:
        half = Fraction(1, 2)
        return (
            self.total_assignments == CANONICAL_ALLOWED_ASSIGNMENT_COUNT
            and self.unique_assignment_count == CANONICAL_ALLOWED_ASSIGNMENT_COUNT
            and len(self.sessions) == CANONICAL_BLOCK_SIZE
            and len({audit.session_id for audit in self.sessions}) == CANONICAL_BLOCK_SIZE
            and all(
                audit.p_self == half
                and audit.p_yoke == half
                and audit.p_receive_high_given_yoke == half
                and audit.p_receive_low_given_yoke == half
                and audit.p_match_given_yoke == half
                and audit.p_mismatch_given_yoke == half
                for audit in self.sessions
            )
        )

    def assert_canonical(self) -> None:
        if not self.is_canonical:
            raise AssertionError("allowed set does not have the canonical assignment probabilities")


def form_canonical_blocks(sessions: Iterable[Session]) -> BlockFormation:
    """Form deterministic 4L/4H blocks separately within each stratum.

    Strata and session IDs are sorted lexicographically.  Within each stratum,
    consecutive groups of four L and four H records form a block.  Invalid
    baseline records and valid records left without complementary support are
    returned explicitly; no record is silently dropped or borrowed across
    strata.
    """

    records = tuple(sessions)
    session_ids = [session.session_id for session in records]
    if len(set(session_ids)) != len(session_ids):
        raise ValueError("session IDs must be globally unique before block formation")

    by_stratum: dict[str, list[Session]] = defaultdict(list)
    for session in records:
        by_stratum[session.stratum].append(session)

    blocks: list[CanonicalBlock] = []
    attrition: list[AttritionRecord] = []

    for stratum in sorted(by_stratum):
        stratum_records = sorted(by_stratum[stratum], key=lambda session: session.session_id)
        low = [session for session in stratum_records if session.baseline_choice == LOW]
        high = [session for session in stratum_records if session.baseline_choice == HIGH]
        invalid = [
            session for session in stratum_records if session.baseline_choice not in {LOW, HIGH}
        ]

        for session in invalid:
            attrition.append(
                AttritionRecord(
                    session=session,
                    reason="invalid_baseline",
                    detail=f"baseline choice {session.baseline_choice!r} is not canonical L or H",
                )
            )

        complete_block_count = min(
            len(low) // CANONICAL_CHOICE_COUNT,
            len(high) // CANONICAL_CHOICE_COUNT,
        )
        for block_offset in range(complete_block_count):
            start = block_offset * CANONICAL_CHOICE_COUNT
            stop = start + CANONICAL_CHOICE_COUNT
            block_sessions = tuple(
                sorted(low[start:stop] + high[start:stop], key=lambda session: session.session_id)
            )
            blocks.append(
                CanonicalBlock(
                    block_id=f"{stratum}::canonical-{block_offset + 1:04d}",
                    stratum=stratum,
                    sessions=block_sessions,
                )
            )

        retained_per_choice = complete_block_count * CANONICAL_CHOICE_COUNT
        unmatched = low[retained_per_choice:] + high[retained_per_choice:]
        unmatched_low_count = len(low) - retained_per_choice
        unmatched_high_count = len(high) - retained_per_choice
        detail = (
            f"stratum retained {complete_block_count} complete block(s); "
            f"unmatched remainder is {unmatched_low_count} L and {unmatched_high_count} H"
        )
        for session in unmatched:
            attrition.append(
                AttritionRecord(
                    session=session,
                    reason="unmatched_block_support",
                    detail=detail,
                )
            )

    attrition.sort(key=lambda record: (record.session.stratum, record.session.session_id))
    formation = BlockFormation(
        blocks=tuple(blocks),
        attrition=tuple(attrition),
        input_session_count=len(records),
    )
    if not formation.accounts_for_all_sessions:
        raise AssertionError("internal error: block formation did not account for every session")
    return formation


@lru_cache(maxsize=32)
def enumerate_allowed_assignments(block: CanonicalBlock) -> tuple[JointAssignment, ...]:
    """Enumerate all 576 allowed donor-aware assignments for ``block``.

    There are 36 ways to choose a 2L/2H self arm.  For each arm split, there
    are 16 bijections from the four self donors to the four yoke recipients
    satisfying the 2x2 recipient-choice by received-schedule table with one
    observation per cell.  Thus each yoke arm has exactly two matches and two
    mismatches, and its received-schedule multiset exactly equals the self
    donors' schedule multiset.
    """

    low_ids = sorted(
        session.session_id for session in block.sessions if session.baseline_choice == LOW
    )
    high_ids = sorted(
        session.session_id for session in block.sessions if session.baseline_choice == HIGH
    )
    choice_by_id: dict[str, Choice] = {
        session.session_id: cast(Choice, session.baseline_choice)
        for session in block.sessions
    }

    allowed: list[JointAssignment] = []
    for self_low in combinations(low_ids, 2):
        for self_high in combinations(high_ids, 2):
            self_ids = tuple(sorted(self_low + self_high))
            self_id_set = set(self_ids)
            yoke_ids = tuple(sorted(set(choice_by_id) - self_id_set))

            # A permutation maps each yoke recipient (in sorted order) to one
            # distinct self donor.  Filtering on all four cells gives exactly
            # the intended zero-association exposure table.
            for donor_order in permutations(self_ids):
                cell_counts = {
                    (LOW, LOW): 0,
                    (LOW, HIGH): 0,
                    (HIGH, LOW): 0,
                    (HIGH, HIGH): 0,
                }
                for recipient_id, donor_id in zip(yoke_ids, donor_order, strict=True):
                    cell_counts[(choice_by_id[recipient_id], choice_by_id[donor_id])] += 1
                if any(count != 1 for count in cell_counts.values()):
                    continue

                rows: list[SessionAssignment] = []
                for self_id in self_ids:
                    choice = choice_by_id[self_id]
                    rows.append(
                        SessionAssignment(
                            session_id=self_id,
                            baseline_choice=choice,
                            arm=SELF,
                            received_schedule=choice,
                            donor_session_id=self_id,
                        )
                    )
                for recipient_id, donor_id in zip(yoke_ids, donor_order, strict=True):
                    rows.append(
                        SessionAssignment(
                            session_id=recipient_id,
                            baseline_choice=choice_by_id[recipient_id],
                            arm=YOKE,
                            received_schedule=choice_by_id[donor_id],
                            donor_session_id=donor_id,
                        )
                    )

                assignment = JointAssignment(
                    block_id=block.block_id,
                    allowed_set_index=len(allowed),
                    sessions=tuple(sorted(rows, key=lambda row: row.session_id)),
                )
                validate_joint_assignment(block, assignment)
                allowed.append(assignment)

    if len(allowed) != CANONICAL_ALLOWED_ASSIGNMENT_COUNT:
        raise AssertionError(
            f"internal error: expected {CANONICAL_ALLOWED_ASSIGNMENT_COUNT} assignments, "
            f"enumerated {len(allowed)}"
        )
    return tuple(allowed)


def validate_joint_assignment(block: CanonicalBlock, assignment: JointAssignment) -> None:
    """Raise ``ValueError`` unless ``assignment`` satisfies every frozen constraint."""

    if assignment.block_id != block.block_id:
        raise ValueError("assignment block_id does not match the block")
    if len(assignment.sessions) != CANONICAL_BLOCK_SIZE:
        raise ValueError("a joint assignment must contain exactly 8 session rows")

    expected = {session.session_id: session.baseline_choice for session in block.sessions}
    observed = {row.session_id: row for row in assignment.sessions}
    if len(observed) != len(assignment.sessions):
        raise ValueError("joint assignment contains duplicate session IDs")
    if set(observed) != set(expected):
        raise ValueError("joint assignment session IDs do not equal the block session IDs")
    if any(observed[session_id].baseline_choice != choice for session_id, choice in expected.items()):
        raise ValueError("joint assignment changed a baseline choice")

    self_rows = [row for row in assignment.sessions if row.arm == SELF]
    yoke_rows = [row for row in assignment.sessions if row.arm == YOKE]
    if len(self_rows) != CANONICAL_ARM_SIZE or len(yoke_rows) != CANONICAL_ARM_SIZE:
        raise ValueError("joint assignment must have equal four-session arms")
    if _row_choice_counts(self_rows) != {LOW: 2, HIGH: 2}:
        raise ValueError("self arm must contain exactly 2 L and 2 H baseline choices")

    for row in self_rows:
        if row.received_schedule != row.baseline_choice or row.donor_session_id != row.session_id:
            raise ValueError("a self row must receive its own baseline schedule")

    self_ids = {row.session_id for row in self_rows}
    yoke_donors = [row.donor_session_id for row in yoke_rows]
    if len(set(yoke_donors)) != len(yoke_donors) or set(yoke_donors) != self_ids:
        raise ValueError("each self schedule must be copied to exactly one yoke recipient")
    for row in yoke_rows:
        if row.received_schedule != expected[row.donor_session_id]:
            raise ValueError("yoke schedule label does not match its donor's schedule")

    self_schedule_counts = _row_schedule_counts(self_rows)
    yoke_schedule_counts = _row_schedule_counts(yoke_rows)
    if self_schedule_counts != yoke_schedule_counts:
        raise ValueError("yoke and self schedule multisets must match exactly")

    yoke_cells = {
        (recipient_choice, schedule): sum(
            row.baseline_choice == recipient_choice and row.received_schedule == schedule
            for row in yoke_rows
        )
        for recipient_choice in (LOW, HIGH)
        for schedule in (LOW, HIGH)
    }
    if any(count != 1 for count in yoke_cells.values()):
        raise ValueError("yoke recipient-choice by schedule table must have one row per cell")
    if sum(row.is_match for row in yoke_rows) != 2:
        raise ValueError("yoke arm must have exactly 2 matches and 2 mismatches")


def sample_assignment(block: CanonicalBlock, seed: int | str | bytes) -> JointAssignment:
    """Draw uniformly from the enumerated set using an explicit deterministic seed.

    The block ID is folded into the random seed so the same master seed does not
    force different blocks to use the same allowed-set index.  ``randrange`` is
    uniform over the 576 enumerated members.
    """

    if not isinstance(seed, (int, str, bytes)):
        raise TypeError("seed must be an int, str, or bytes")
    seed_material = f"binding-test-assignment-v1|{type(seed).__name__}|{seed!r}|{block.block_id}"
    rng = random.Random(seed_material)
    allowed = enumerate_allowed_assignments(block)
    return allowed[rng.randrange(len(allowed))]


def audit_assignment_probabilities(
    block: CanonicalBlock,
    assignments: Sequence[JointAssignment] | None = None,
) -> AssignmentProbabilityAudit:
    """Calculate exact assignment and exposure probabilities by enumeration."""

    allowed = tuple(assignments) if assignments is not None else enumerate_allowed_assignments(block)
    if not allowed:
        raise ValueError("cannot audit an empty assignment set")
    for assignment in allowed:
        validate_joint_assignment(block, assignment)

    session_audits: list[SessionProbabilityAudit] = []
    for session in sorted(block.sessions, key=lambda record: record.session_id):
        rows = [assignment.for_session(session.session_id) for assignment in allowed]
        total = len(rows)
        yoke_rows = [row for row in rows if row.arm == YOKE]
        if not yoke_rows:
            raise ValueError(f"session {session.session_id!r} has zero yoke probability")

        yoke_total = len(yoke_rows)
        session_audits.append(
            SessionProbabilityAudit(
                session_id=session.session_id,
                p_self=Fraction(sum(row.arm == SELF for row in rows), total),
                p_yoke=Fraction(yoke_total, total),
                p_receive_high_given_yoke=Fraction(
                    sum(row.received_schedule == HIGH for row in yoke_rows), yoke_total
                ),
                p_receive_low_given_yoke=Fraction(
                    sum(row.received_schedule == LOW for row in yoke_rows), yoke_total
                ),
                p_match_given_yoke=Fraction(sum(row.is_match for row in yoke_rows), yoke_total),
                p_mismatch_given_yoke=Fraction(
                    sum(not row.is_match for row in yoke_rows), yoke_total
                ),
            )
        )

    return AssignmentProbabilityAudit(
        total_assignments=len(allowed),
        unique_assignment_count=len(
            {
                tuple(
                    (
                        row.session_id,
                        row.arm,
                        row.received_schedule,
                        row.donor_session_id,
                    )
                    for row in assignment.sessions
                )
                for assignment in allowed
            }
        ),
        sessions=tuple(session_audits),
    )


def _choice_counts(sessions: Sequence[Session]) -> defaultdict[str, int]:
    counts: defaultdict[str, int] = defaultdict(int)
    for session in sessions:
        counts[session.baseline_choice] += 1
    return counts


def _row_choice_counts(rows: Sequence[SessionAssignment]) -> dict[str, int]:
    return {
        LOW: sum(row.baseline_choice == LOW for row in rows),
        HIGH: sum(row.baseline_choice == HIGH for row in rows),
    }


def _row_schedule_counts(rows: Sequence[SessionAssignment]) -> dict[str, int]:
    return {
        LOW: sum(row.received_schedule == LOW for row in rows),
        HIGH: sum(row.received_schedule == HIGH for row in rows),
    }
